server:
  port: 30001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL.HOST:localhost}:3306/${MYSQL.DATABASE:security}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL.USERNAME:root}
    password: ${MYSQL.PASSWORD:root}
  redis:
    database: 0
    host: ${REDIS.HOST:localhost}
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  session:
    store-type: none
#  security:
#    user:
#      name: admin
#      password: admin123

mybatis:
  type-aliases-package: com.cloud.**.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#swagger配置
swagger:
  enable: true
  basePackage: com.cloud
  groupName: 安全认证服务文档

#security配置
security:
  register:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeD3OIrbUGE4_CEGkGmVVLGFMhop9-RvgU18sgEH1T2Dc-2uTAtMUA5vbiPnpD8L4RxVbkMJtlx0ULbrqwCOPEcnM-Ri3h3nR6kRTRDdy82BYiANDV5UTiqZ0lul10rSvf5NjwnSxK5DeRySrOQci6nLGa654paY7RxVHpg3_oqwIDAQAB
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJ4Pc4ittQYTj8IQaQaZVUsYUyGin35G-BTXyyAQfVPYNz7a5MC0xQDm9uI-ekPwvhHFVuQwm2XHRQtuurAI48Rycz5GLeHedHqRFNEN3LzYFiIA0NXlROKpnSW6XXStK9_k2PCdLErkN5HJKs5ByLqcsZrrnilpjtHFUemDf-irAgMBAAECgYBUyc0cQLKe89dmLw9n7tEGW6IcpPQR9VgXNjtMlAvm8lGQcjPL_CzB8yP08bb8wyPyvH2EI175FhA_tcKHs_0aCMKBRZvZTVLYQ08SneCRhUZmMBGk3Vix0_Zs3hFaoDKNxstj1O73DUeWLy9wZFtqbNCEGZ-BkIHOqCtlOxxXQQJBAMyiyXYRAhiADfvzMhrhQNt6krHAn9kJnS6Pwmh-d7mWZdJPUYlnXCTO-K4Pg9ZqPWYhscteCePvddSeFHnmgwkCQQDFu-CrqpYhgDlGDjVEsL99jgxzcc9aKjV0s2DmDf6Zt6_jzxIoKsp7flwuM8oz0x-vAuYNUhJMTfRR6h2EY3cTAkEAtPyI5-Z1Dww60gou130_6p4HHjU6ay_ImATHsbmg1ECDf7VtbPRAl8GCShgoxzuhYDIO2MosPy9r7Id_nqzUWQJAfvImxK-JIUrr-lEG2-nJlrcKwVcw80cj-J9tN2WGrnOihdQcaRNH2c7_KV5wk6MYtUhcH_Mv8jMeBzUR7DvbZwJAL6XRW5vQnXd0QgL5s5ZOTi26BQOsY_5MKtudTxTG0hXIxtFtimlIghpBhMmiFKS9gov-zSWylyeQ9sx6PdJdHQ
  ignore:
    uris:
      - /actuator/**
      - /swagger-ui.html/**
      - /doc.html/**
      - /swagger-resources/**
      - /webjars/**
      - /images/**
      - /configuration/ui
      - /configuration/security
      - /v2/api-docs
      - /csrf
      - /favicon.ico
      - /error
      - /index.html/**
      - /static/**
      - /favicon.ico
      - /sysuser/**


